[[language]]
name = "hcl"
scope = "source.hcl"
injection-regex = "(hcl|tf|nomad|tfvars)"
file-types = ["hcl", "tf", "nomad", "tfvars"]
roots = []
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-server = { command = "terraform-ls", args = ["serve"], language-id = "terraform" }
auto-format = false

[[grammar]]
name = "hcl"
source = { git = "https://github.com/MichaHoffmann/tree-sitter-hcl", rev = "3cb7fc28247efbcb2973b97e71c78838ad98a583" }

[[language]]
name = "tfvars"
scope = "source.tfvars"
file-types = ["tfvars"]
roots = []
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-server = { command = "terraform-ls", args = ["serve"], language-id = "terraform-vars" }
auto-format = false
grammar = "hcl"